### PR TITLE
Update equivalent circuits

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
need to add a loop to cover both with AND without faradaic processes

**Comment by dalg24** [comment]
Note that I removed the method `EnergyStorageDevice.compute_equivalent_circuit` from the Python wrappers.

To build an equivalent circuit to a supercap, all you need is:

```
>>> ptree = PropertyTree()
>>> ptree.parse_info('super_capacitor.info')
>>> ptree.put_string('type', 'EquivalentCircuit') # <-- override ``type``
>>> equivalent_circuit = EnergyStorageDevice(ptree)
```

Much cleaner IMO.

**Comment by Rombur** [comment]
I don't know. It's shorter but I find that a very unexpected behavior. If I see the command `put_string`, I expect the type to be changed and that's it. I find that `put_string` having different behavior depending on the key is confusing. This is not the behavior I would expect from a property tree. It won't keep me awake at night, though. So if you really want this, I won't fight it.

**Comment by dalg24** [comment]
Say you have a ptree for your high fidelity model and you want to "calibrate" your experience (choose an appropriate charge current and max duration for instance), that's very convenient to be able to do this.
What we had before was

```
>>> ptree = PropertyTree()
>>> ptree.parse_info('super_capacitor.info')
>>> other = EnergyStorageDevice.compute_equivalent_circuit(ptree) # <-- cumbersome
>>> equivalent_circuit = EnergyStorageDevice(other)
```

**Comment by dalg24** [comment]
"If I see the command put_string, I expect the type to be changed and that's it. I find that put_string having different behavior depending on the key is confusing."

I believe you misunderstood me here.
The command

```
>>> ptree.put_string('type', 'EquivalentCircuit')
```

is setting the node `type` to `EquivalentCircuit`. It adds it if it didn't already exist and replace it otherwise. That's the normal behavior for a Boost.PropertyTree

**Comment by Rombur** [comment]
OK I understand. It's the override that got me confused. I thought that `put_string` was calling `compute_equivalent_circuit` (I thought you meant that you overrode the behavior of `put_string` when the key is type).

**Comment by dalg24** [comment]
No that would be silly ;)

**Comment by Rombur** [comment]
You have used me to worse... jk

**Pull request merged**
