### PR TITLE
Use docker-compose in Jenkins builds

### PR DESCRIPTION
**Pull request by dalg24**
We were relying on the script `docker-run.py` for out Jenkins build.  That Python script was using the Docker Python API and was essentially used to launch CI containers, execute instruction, and cleanup (stop and remove containers).  It was using a Python dictionary to configure which was quite flexible but needed additional work to be able to extend configuration (to work with NVIDIA plugin for instance).
Here we decide to take advantage of `docker-compose` which seems to be already doing all I was trying to achieve with our script.

### CODE REVIEW

**Comment by dalg24** [comment]
Mounting point is wrong.  Jenkins does not find the build directory when looking for the test results.

**Comment by dalg24** [comment]
The good news is that when I fix that the plugin for the warnings will fully work at last...

**Comment by dalg24** [comment]
Ready for review

**Review by Rombur — APPROVED** [review]
Very nice. It's great that we can do everything with docker-compose.

**Pull request merged**
