### PR TITLE
Run cppcheck on Jenkins

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
Wait before you merge. Need to make sure Jenkins picked it up

**Comment by dalg24** [comment]
looks like github is experiencing some difficulties :(

**Comment by Rombur** [comment]
Looks good to me. If you are satisfied with the result on jenkins, merge yourself.

**Comment by dalg24** [comment]
http://jupyterdocker.ornl.gov:8080/job/Cap-experimental/48/cppcheckResult/

**Pull request merged**
