### PR TITLE
Improve Python coverage

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
low hanging fruits :)

**Comment by dalg24** [comment]
not sure how to deal with these "assert does not raise".
should we just [exclude the lines](http://coverage.readthedocs.org/en/coverage-4.0.3/excluding.html)?

**Comment by Rombur** [comment]
I don't really care. I just want to see which part of the code needs more testing. If one file has just 20% testing because we don't raise the asserts, it's fine with me.

**Comment by dalg24** [comment]
In the process of removing `measure_impedance_spectrum` which is deprecated in favor of `ElectrochemicalImpedanceSpectroscopy`

**Comment by dalg24** [comment]
arrggh, forgot to add the template file :(

**Comment by Rombur** [comment]
If you just change the title, I don't get an e-mail. You need to add a comment to let me know it's ready for review.

**Pull request merged**
